# Generated by Django 4.2.11 on 2024-03-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Iniciante", "Iniciante"),
                    ("Intermediario", "Intermediario"),
                    ("Avançado", "Avançado"),
                ],
                max_length=50,
            ),
        ),
    ]
